apiVersion: v1
kind: Namespace
metadata:
  name: ingress-weight
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ingress-weight
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;
        server_name localhost;

        location / {
          default_type text/plain;
          return 200 "nginx-v1";
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-v1
  namespace: ingress-weight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: nginx
        image: shixiaochuangk8s/nginx:1.28.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-v1-svc
  namespace: ingress-weight
spec:
  selector:
    app: nginx-v1
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP