apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod-3
  namespace: pod-ns
spec:
  containers:
    - name: app
      image: shixiaochuangk8s/nginx:1.17.3
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        #  未设置 limits → limits = 节点最大值 → requests != limits