apiVersion: v1
kind: Pod
metadata:
  name: downward-api-pod
  namespace: pod-ns
spec:
  containers:
    - name: app
      image: shixiaochuangk8s/busybox:1.28.3
      command: [ "sh", "-c", "printenv | grep POD_ && sleep 3600" ]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName