apiVersion: v1
kind: Pod
metadata:
  name: restart-never-pod
  namespace: pod-ns
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: shixiaochuangk8s/busybox:1.28.3
      command: [ "sh", "-c", "echo 'One-time task'; sleep 3; exit 1" ]