apiVersion: v1
kind: Pod
metadata:
  name: pod-never
  namespace: pod-ns
spec:
  containers:
  - name: nginx
    image: shixiaochuangk8s/nginx:1.14-alpine
    imagePullPolicy: Never  # 仅使用节点本地镜像，不联网拉取