apiVersion: v1
kind: Pod
metadata:
  name: override-command
  namespace: pod-ns
spec:
  containers:
    - name: c1
      image: shixiaochuangk8s/demo-entrypoint:v1.1
      command: [ "echo", "NEWENTRY" ]