apiVersion: v1
kind: Pod
metadata:
  name: over-request-pod
  namespace: pod-ns
spec:
  containers:
    - name: huge-app
      image: shixiaochuangk8s/httpd:2.2
      resources:
        requests:
          memory: "10Gi"  # 超出节点可用内存
          cpu: "8"