apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  namespace: pod-ns
  labels:
    app: web
    tier: frontend
    env: production
    version: v1
spec:
  containers:
    - name: nginx
      image: shixiaochuangk8s/nginx:1.18