apiVersion: v1
kind: Pod
metadata:
  name: volume-nfs
  namespace: volume-ns
spec:
  containers:
  - name: nginx
    image: shixiaochuangk8s/nginx:1.17.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs-volume
      mountPath: /var/log/nginx
  - name: busybox
    image: shixiaochuangk8s/busybox:1.30
    command: ["/bin/sh","-c","tail -f /logs/access.log"]
    volumeMounts:
    - name: logs-volume
      mountPath: /logs
  volumes:
  - name: logs-volume
    nfs:
      server: 192.168.200.135  #nfs服务器地址
      path: /opt/data/nfs #共享文件路径