apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nacos-ns
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "nacos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: nacos-ns
data:
  MYSQL_USER: "nacos"
  MYSQL_DATABASE: "nacos"