apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-cfg
  namespace: gateway-api
data:
  traefik.yaml: |-
    api:
      # 开启 Traefik Dashboard 仪表盘
      dashboard: true

    # Ping 探针配置，用于 Kubernetes 存活/就绪检查
    ping: {}

    # 入口点配置，定义 Traefik 监听的端口
    entryPoints:
      # 定义名为 web 的入口点（通常用于 HTTP）
      web:
        # 监听所有网络接口的 80 端口
        address: ":80"
      # 定义名为 websecure 的入口点（通常用于 HTTPS）
      websecure:
        # 监听所有网络接口的 443 端口
        address: ":443"
        # HTTP 协议相关配置
        http:
          # 启用 TLS（即开启 HTTPS 加密）
          tls: {}

    # 提供者配置，定义后端服务发现的来源
    providers:
      # 启用 Kubernetes Gateway API 作为服务提供者
      kubernetesGateway: {}

    # 全局日志配置
    log:
      # 设置日志级别为 info
      level: info
      # 设置日志输出格式为 json
      format: json

    # 访问日志配置
    accessLog:
      # 设置访问日志输出格式为 json
      format: json