apiVersion: v1
kind: Pod
metadata:
  name: pod-restartpolicy
  namespace: pod-ns
spec:
  containers:
    - name: nginx
      image: shixiaochuangk8s/nginx:1.14-alpine
      ports:
        - name: nginx-port
          containerPort: 80
      livenessProbe:
        httpGet: # 其实就是访问http://127.0.0.1:80/hello
          scheme: HTTP #支持的协议，http或者https
          port: 80 #端口号
          path: /hello #URI地址
  restartPolicy: Never # 设置重启策略为Never