apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness-exec
  namespace: pod-ns
spec:
  containers:
  - name: nginx
    image: shixiaochuangk8s/nginx:1.14-alpine
    ports:
    - name: nginx-port
      containerPort: 80
    livenessProbe:
      exec:
        command: ["/bin/cat","/tmp/hello.txt"] # 执行一个查看文件的命令