---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
stringData:
  userID: fsclient
  userKey: AQCvjp1pA24iHRAAynC4TvV/2+M/TuDdU+emQw==

  adminID: admin
  adminKey: AQDrHlBp/RjZKxAA0KxMFXxyg134MR6enoN1zA==