apiVersion: v1
kind: Secret
metadata:
  name: sky-server-secrets
  namespace: javaproject
type: Opaque
stringData:
  MYSQL_PASSWORD: "sky_take_out"
  REDIS_PASSWORD: "123321"
  ALIOSS_ACCESS_KEY_ID: ""
  ALIOSS_ACCESS_KEY_SECRET: ""
  WECHAT_SECRET: ""