apiVersion: apps/v1
kind: Deployment
metadata:
  name: pc-deployment
  namespace: service-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod-yaml
  template:
    metadata:
      labels:
        app: nginx-pod-yaml
    spec:
      containers:
      - name: nginx
        image: shixiaochuangk8s/nginx:1.17.1
        ports:
        - containerPort: 80