expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  ingress:
    hosts:
      core: harbor.shixiaochuang.org
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

externalURL: https://harbor.shixiaochuang.org

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: 200Gi

    chartmuseum:
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: 10Gi

    jobservice:
      jobLog:
        storageClass: "rook-ceph-block"
        accessMode: ReadWriteOnce
        size: 5Gi

    database:
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: 20Gi

    redis:
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: 5Gi

    trivy:
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: 20Gi

harborAdminPassword: "shixiaochuang.org"