apiVersion: v1
kind: Pod
metadata:
  name: security-context-container-demo
  namespace: sc-ns
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: sec-ctx-demo
      image: shixiaochuangk8s/busybox:1.30
      command: [ 'sh', '-c', 'sleep 60m' ]
      securityContext:
        runAsUser: 2000
        allowPrivilegeEscalation: false