apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: gitlab-ns
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
        - name: postgresql
          image: shixiaochuangk8s/postgres:18
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: db_pass
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: db_name
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        storageClassName: "nfs-csi"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: gitlab-ns
  labels:
    name: postgresql
spec:
  clusterIP: None
  selector:
    name: postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres