apiVersion: v1
kind: Pod
metadata:
  name: pod-podaffinity-preferred
  namespace: pod-scheduler
spec:
  containers:
  - name: nginx
    image: shixiaochuangk8s/nginx:1.17.1
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:   # 软限制
      - weight: 100   # 权重，1~100，值越大表示优先级越高
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: podenv
              operator: In
              values: ["xxx", "yyy"]
          topologyKey: kubernetes.io/hostname