apiVersion: v1
kind: Pod
metadata:
  name: pod-podaffinity-target
  namespace: pod-scheduler
  labels:
    podenv: pro #设置标签
spec:
  containers:
  - name: nginx
    image: shixiaochuangk8s/nginx:1.17.1
  nodeName: work01.shixiaochuang.org # 将目标pod名确指定到work01上