apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: project-ns
data:
  SERVER_PORT: "8080"
  REDIS_HOST: "redis-0"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  MYSQL_HOST: "db-0"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "dkd"
  MYSQL_USERNAME: "dkd"
  OSS_ENDPOINT: "oss-cn-xxx.aliyuncs.com"
  OSS_BUCKET: "dkd-bucket"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: project-ns
type: Opaque
stringData:
  REDIS_PASSWORD: "123321"
  MYSQL_PASSWORD: "dkd"
  OSS_ACCESS_KEY: "xxx"
  OSS_SECRET_KEY: "xxx"