apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app: traefik
  name: nginxweb-app
  namespace: gateway-api-ns
spec:
  parentRefs:
    - name: example-gateway
  hostnames:
    - canary.shixiaochuang.org
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: svc1
          port: 80
          weight: 3  # 3份流量到 svc1
        - name: svc2
          port: 80
          weight: 1  # 1份流量到 svc2