apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: project-ns
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "exam_system"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: project-ns
data:
  MYSQL_USER: "exam_system"
  MYSQL_DATABASE: "exam_system"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project-ns
spec:
  clusterIP: None
  selector:
    app: mysql-public
  ports:
    - port: 3306
      name: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: project-ns
spec:
  serviceName: "mysql"
  selector:
    matchLabels:
      app: mysql-public
  template:
    metadata:
      labels:
        app: mysql-public
    spec:
      securityContext:
        fsGroup: 999
      serviceAccountName: harbor-sa
      containers:
        - name: mysql
          image: harbor.shixiaochuang.org/env/mysql:8.0.33
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE

          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysql-data

  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: csi-rbd-sc
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi