apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-maven-repo-pvc
  namespace: jenkins-ns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-csi