apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins-ns
spec:
  serviceAccountName: harbor-sa

  securityContext:
    runAsUser: 1000
    fsGroup: 995

  containers:
  - name: agent
    image: harbor.shixiaochuang.org/jenkins/jenkins-slave-agent:jdk17-maven-sonar-docker

    envFrom:
    - configMapRef:
        name: jenkins-slave-config
    - secretRef:
        name: jenkins-slave-secret

    volumeMounts:
    - name: ssh-key
      mountPath: /home/jenkins/.ssh/id_rsa
      subPath: id_rsa
      readOnly: true

    - name: ssh-key
      mountPath: /home/jenkins/.ssh/known_hosts
      subPath: known_hosts
      readOnly: true
    - name: docker-sock
      mountPath: /var/run/docker.sock

    - name: maven-repo
      mountPath: /home/jenkins/.m2/repository

  volumes:
  - name: ssh-key
    secret:
      secretName: agent-ssh
      defaultMode: 0600
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket

  - name: maven-repo
    persistentVolumeClaim:
      claimName: jenkins-maven-repo-pvc