apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-slave-config
  namespace: jenkins-ns
data:
  # Maven 私服地址
  MAVEN_REPO_URL: "http://nexus.nexus-ns.svc.cluster.local:8081/repository/maven-public/"
  # SonarQube 配置
  SONAR_HOST_URL: "http://sonarqube.sonarqube-ns.svc.cluster.local:9000"
  SONAR_SOURCE_ENCODING: "UTF-8"
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-slave-secret
  namespace: jenkins-ns
type: Opaque
stringData:
  SONAR_TOKEN: "sqa_ec61dcc62291fd684937d9d38fdf8a4d732d5a80"