apiVersion: v1
kind: Service
metadata:
  name: openelb-nginx
  namespace: service-ns
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    protocol.openelb.kubesphere.io/v1alpha1: layer2
    eip.openelb.kubesphere.io/v1alpha2: eip-pool
spec:
  selector:
    app: openelb-nginx
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80