apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: harbor-ns
  labels:
    app: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      serviceAccountName: harbor-sa
      containers:
        - name: nginx
          image: harbor.shixiaochuang.org/nginx/nginx:1.15-alpine
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: harbor-ns
  labels:
    app: nginx2
spec:
  type: NodePort
  selector:
    app: nginx2
  ports:
    - port: 8099
      targetPort: 80
      protocol: TCP
      nodePort: 30090