apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: gitlab-ns
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: shixiaochuangk8s/redis:7.4.2
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: /var/lib/redis
          name: redis-data
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redis-config
          subPath: redis.conf
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -a $REDIS_PASSWORD ping | grep PONG"
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -a $REDIS_PASSWORD ping | grep PONG"
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      storageClassName: "nfs-csi"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: gitlab-ns
  labels:
    name: redis
spec:
  clusterIP: None
  selector:
    name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis