apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql-secret2
  namespace: secret-ns
spec:
  containers:
    - name: busybox
      image: shixiaochuangk8s/busybox:1.30
      args:
        - /bin/sh
        - -c
        - sleep 100000
      volumeMounts:
        - name: vol-secret                  # 定义挂载的卷,对应下面定义的卷名
          mountPath: "/opt/passwd"    # 挂载目录(支持热更新),也可以使用subPath挂载文件(但不支持热更新)
          readOnly: true                    # 只读
  volumes:
    - name: vol-secret                    # 定义卷名
      secret: # 使用secret
        secretName: secret-redis        # 对应创建好的secret名