apiVersion: v1
kind: Pod
metadata:
  name: redis-secret1
  namespace: secret-ns
spec:
  containers:
    - name: redis
      image: shixiaochuangk8s/redis:6.2
      args: [ "--requirepass", "$(REDIS_PASSWORD)" ]   # 启动时启用密码认证
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-redis
              key: password
      ports:
        - containerPort: 6379