apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: rbac-ns
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: shixiaochuangk8s/nginx:1.25
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: rbac-ns
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8099
      targetPort: 80
      protocol: TCP
      nodePort: 30080