apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: redis
type: "kubernetes.io/rbd"
data:
  key: QVFDdmRKNXBNQ1ZGSnhBQVRDdE82cURiRzFkMjY0S2RMQXdMeEE9PQ==
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-with-rdb-test
  namespace: redis
spec:
  nodeName: work02.shixiaochuang.org
  containers:
  - name: redis
    image: shixiaochuangk8s/redis:6.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: "/data"  # 将 Ceph 存储挂载到容器内的 "/data" 路径
      name: redis-cephrbd-vol  # 挂载的卷的名称为 "redis-cephrbd-vol"
  volumes:
  - name: redis-cephrbd-vol  # 卷的名称为 "redis-cephrbd-vol"
    rbd:  # 使用 Ceph RBD 卷
      monitors:
      - 192.168.200.248:6789  # Ceph Monitor 节点的 IP 地址和端口
      - 192.168.200.247:6789
      - 192.168.200.246:6789
      pool: kube-rbddata  # 使用的 Ceph Pool 名称是 "kube-rbddata"
      image: kubeimg02  # Ceph RBD 镜像的名称是 "kubeimg"
      fsType: xfs  # 使用的文件系统类型是 XFS
      user: k8s  # 访问 Ceph 存储的用户是 "k8s"
      secretRef:
        name: ceph-secret