apiVersion: v1
kind: Secret

metadata:
  name: csi-rbd-secret
  namespace: default

# stringData 表示以“明文字符串”的方式定义 Secret
# Kubernetes 会在保存时自动进行 base64 编码
stringData:
  # Ceph 用户名（CephX 用户）
  # 一般在 Ceph 集群中通过 `ceph auth get-or-create` 创建
  userID: kubernetes

  # Ceph 用户的密钥（CephX key）
  # 用于 Ceph CSI 访问 RBD Pool 的鉴权
  userKey: AQD+d55pjEG2IBAAPFwzsAc3pMtej+0N0Vt9pQ==

  # 加密口令（可选）
  # 当 StorageClass 启用 volume 加密（encryption）时使用
  # 通常配合 KMS（如 Vault）或 Ceph 内置加密
  encryptionPassphrase: test_passphrase