apiVersion: v1
kind: Secret
metadata:
  name: metrics-password
  namespace: mongodb-ns
type: Opaque
stringData:
  password: "YourSecureMetricsPass2026!"
  # 可选：同时定义 username（如果 Prometheus 需要）
  username: "prometheus"