apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: my-mongo
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            # 固定名称，不能改！
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: csi-rbd-sc
            resources:
              requests:
                storage: 10Gi
        - metadata:
            # 固定名称，不能改！
            name: logs-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: csi-rbd-sc
            resources:
              requests:
                storage: 2Gi
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongo-password
        key: password
      scramCredentialsSecretName: my-mongo-scram
      roles:
        - name: root
          db: admin

  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib