apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: pod-controller
  labels:
    app: nginx
spec:
  ports:
    - name: http
      port: 80
  clusterIP: None
  selector:
    app: nginx-web