apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
  namespace: pod-controller
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: counter
        image: shixiaochuangk8s/busybox:1.30
        command:
        - "bin/sh"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"