apiVersion: batch/v1
kind: Job
metadata:
  name: job-failed-demo
  namespace: pod-controller
spec:
  template:
    spec:
      containers:
      - name: test-job
        image: shixiaochuangk8s/busybox:1.28.3
        command: ["echo123", "test failed job!"]
      restartPolicy: Never