apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hpa
  namespace: pod-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hpa
  template:
    metadata:
      labels:
        app: nginx-hpa
    spec:
      containers:
        - name: nginx
          image: shixiaochuangk8s/nginx:1.25
          resources:
            requests:
              cpu: "100m"