apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pc-daemonset
  namespace: pod-controller
spec:
  selector:
    matchLabels:
      app: nginx-daemon
  template:
    metadata:
      labels:
        app: nginx-daemon
    spec:
      containers:
      - name: nginx
        image: shixiaochuangk8s/nginx:1.17.1