apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: seata-ns
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_PASSWORD: "seata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: seata-ns
data:
  MYSQL_USER: "seata"
  MYSQL_DATABASE: "seata"