---
apiVersion: v1
kind: Pod
metadata:
  name: cephcsi-nfs-demo-pod
  namespace: nfs-ns
spec:
  containers:
    - name: web-server
      image: shixiaochuangk8s/nginx:1.15-alpine
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephcsi-nfs-pvc
        readOnly: false