apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-headless-statefulset
  namespace: service-ns
spec:
  serviceName: headless-service-statefulset  # 必须加上这个字段
  replicas: 2
  selector:
    matchLabels:
      app: headless-statefulset
  template:
    metadata:
      labels:
        app: headless-statefulset
    spec:
      containers:
        - name: nginx-smart
          image: shixiaochuangk8s/nginx:1.15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: headless-service-statefulset
  namespace: service-ns
spec:
  clusterIP: None
  selector:
    app: headless-statefulset
  ports:
    - port: 80