apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-env
  namespace: service-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-env
  template:
    metadata:
      labels:
        app: nginx-env
    spec:
      containers:
        - name: nginx
          image: shixiaochuangk8s/nginx:1.14-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-dnv
  namespace: service-ns
spec:
  ports:
    - port: 5000
      targetPort: 80
  selector:
    app: nginx-env